pipeline {
  agent any
    tools {
	 maven 	'maven_3.9.4'
	 }
	 stages {
	  stage('code compilation') {
	    steps {
		     echo ' code compilation is in now progress'
             sh ' mvn clean compile'
			 echo ' Code compilation is now completed '
			 }
			 }
			 stage ('Code QA ') {
			  steps {
			          echo ' Code QA is WIP '
					  sh 'mvn clean test'
					  echo 'code QA completed'
					  }
					  }
					  stage ('Code Package'){
					   steps {
					   echo ' mvn clean package'
						echo 'Creating war artifacts '
				}
		}

	stage('Building & Tag Docker Image') {
                steps {
                    echo 'Starting Building Docker Image'
                    sh 'docker build -t pra4188/makemytrip.'
                    sh 'docker build -t pra4188/makemytrip.'
                    echo 'Completed  Building Docker Image'
                }
            }
            stage('Docker Image Scanning') {
                steps {
                    echo 'Docker Image Scanning Started'
                    sh 'java -version'
                    echo 'Docker Image Scanning Started'
                }
            }
	}
}