pipeline {
  agent { label 'TeamA_Slave' }
    tools {
	 maven 	'maven_3.9.4'
	 }
	 stages {
	  stage('code compilation') {
	    steps {
		     echo ' code compilation is in now progress'
             sh ' mvn clean compile'
			 echo ' Code compilation is now completed '
			 }
			 }
			 stage ('Code QA ') {
			  steps {
			          echo ' Code QA is in progress '
					  sh 'mnvn clean test'
					  echo 'code QA completed'
					  }
					  }
					  stage ('Code Package'){
					   steps {
					   echo ' mvn clean package'
						echo 'creating war artifact '
				}
		}
	}
}